[package]
name = "offscreen-canvas"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
image = { version = "0.24.7", default-features = false, features = ["png"]}
imageproc = { version = "0.23.0", default-features = false}
fontdue = "0.8"