[package]
name = "hello-slint"
version = "1.0.0"
edition = "2021"

[dependencies]
slint = "1.4.1"
anyhow = "1"
offscreen-canvas = { path = "../../"}
image = "0.24.8"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.87"

# [lib]
# crate-type = ["cdylib"]
# path = "src/main.rs"